name: saurav
description: >-
  Assignment 2
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  io: ^1.0.0  #Input Out operation form cmd
  json_serializable: ^4.1.3  # convert json data to object and object to json
  
